;;; init.el --- Main entry point -*- lexical-binding: t; -*-

(let ((config-dir (file-name-directory (or load-file-name buffer-file-name))))
  (add-to-list 'load-path (expand-file-name "modules" config-dir))
  (add-to-list 'load-path (expand-file-name "packages/orbit-context" config-dir)))

(require 'mod-core)
(require 'mod-theme)
(require 'mod-home)
(require 'mod-ui)
(require 'mod-dired)
(require 'mod-evil)
(require 'mod-pairs)
(require 'mod-git)
(require 'mod-utility)
(require 'mod-shell)
(require 'mod-keys)
(require 'mod-completion)
(require 'mod-snippets)
(require 'mod-org)
(require 'mod-roam)
(require 'mod-mermaid)
(require 'mod-jira)
(require 'mod-project)
(require 'mod-search)
(require 'mod-markdown)
(require 'mod-python)
(require 'mod-tcl)
(require 'mod-tcl-docs)
(require 'orbit-context)
(require 'mod-session)
(when (fboundp 'orbit-startup--finish)
  (orbit-startup--finish))

;;; init.el ends here
